version: '3.4'

services:
  detectron2_header:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    image: "${IMAGE_NAME}:${IMAGE_VERSION}"
    tty: true
    container_name: "${IMAGE_NAME}_${IMAGE_VERSION}"
    volumes:
      - "${DATASET_STORAGE}:/mnt/dataset-storage"
    deploy:
      resources:
        limits:
          memory: "$MEMORY"
          cpus: "$CPU"
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
