version: "3.4"

services:
  detectron2_header:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    image: "detectron2_header:1.0v"
    tty: true
    container_name: "${IMAGE_NAME}_${IMAGE_VERSION}"
    volumes:
      - "${DATASET_STORAGE}:/home/appuser/mnt/dataset-storage"
    deploy:
      resources:
        limits:
          memory: "8gb"
          cpus: "12"
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
