version: "3.4"

services:
  detectron2_header:
    build:
      context: ..
      dockerfile: Dockerfile
    image: "detectron2_header:1.0v"
    tty: true
    container_name: "detectron2_header_gpu7"
    deploy:
      resources:
        limits:
          memory: "8gb"
          cpus: "12"
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["7"]
              capabilities: [gpu]
